version: '3.8'
services:
    client:
        build:
            context: client
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        environment:
            - FAST_REFRESH=false # Source: https://stackoverflow.com/questions/43274925/development-server-of-create-react-app-does-not-auto-refresh
        volumes:
            - ./client/src:/app/src
